#21/fix : 주문과 견적에 관한 CRUD 추가
GrassHopper42/simon pull request #32
Opened 2023-09-10 12:27 UTC by constwon111

- [x] 주문취소
- [x] 주문생성
- [x] 주문상태 변경
- [x] 주문취소 되돌리기 
- [x] 견적 생성

2023-09-12 08:32 UTC, GrassHopper42 requested changes
Estimation이랑 Order도메인 합친 후에 다시 리뷰하겠습니다!

2023-09-13 09:48 UTC, constwon111 commented
> Estimation이랑 Order도메인 합친 후에 다시 리뷰하겠습니다!

Estimation이랑 Order랑 합치게 됐을때 FK로 엮나요? 만약 그렇게 되면 Order나 Estimation이 공통적으로 가지고 있던 프로퍼티들은 Order가 가지는게 맞을까요? 아니면 Estimation이 가지는게 맞을까요?

견적만 있는 상태는 있고, 견적없이 주문만 있는 상태는 없다보니 견적에 프로퍼티들을 추가하는게 맞는것 같은데, 만약 저번에 얘기하신것처럼 배치를 돌려서 주문완료된 견적들은 일정 주기대로 삭제할 예정이라면 얘기가 또 달라질것 같아 질문드립니다!

2023-09-13 11:21 UTC, AnTaeWook commented on src/main/java/dau/azit/simon/estimation/controller/EstimationController.java
> +	public ResponseEntity<SalesOrder> createEstimation(@Valid @RequestBody() CreateEstimationDto dto) {
어노테이션 공백 괄호가 필요한 이유가 있나요?(빼셈)

2023-09-13 11:24 UTC, AnTaeWook commented on src/main/java/dau/azit/simon/estimation/domain/Estimation.java
> +	@ManyToOne()
위 리뷰와 동일(공백 괄호)

2023-09-13 11:27 UTC, AnTaeWook commented on src/main/java/dau/azit/simon/order/controller/SalesOrderController.java
> +		return ResponseEntity.ok(null);
위 리뷰와 동일 (생성 자원 반환)

2023-09-13 11:49 UTC, GrassHopper42 commented
> > Estimation이랑 Order도메인 합친 후에 다시 리뷰하겠습니다!
> 
> Estimation이랑 Order랑 합치게 됐을때 FK로 엮나요? 만약 그렇게 되면 Order나 Estimation이 공통적으로 가지고 있던 프로퍼티들은 Order가 가지는게 맞을까요? 아니면 Estimation이 가지는게 맞을까요?
> 
> 견적만 있는 상태는 있고, 견적없이 주문만 있는 상태는 없다보니 견적에 프로퍼티들을 추가하는게 맞는것 같은데, 만약 저번에 얘기하신것처럼 배치를 돌려서 주문완료된 견적들은 일정 주기대로 삭제할 예정이라면 얘기가 또 달라질것 같아 질문드립니다!
> 
> 만약 주문으로 이어진 견적은 삭제되지 않고, 주문으로 이어지지 않은 견적만 삭제되도록 배치 처리를 하면 상관 없을것 같기도 합니다!

견적은 주문과는 관계없이 삭제하는 것으로 구상했습니다. 회의 때 제안한 아이디어라면 Estimation의 PK로 Order의 PK를 사용하는 방식을 제안했습니다.

2023-09-13 12:00 UTC, constwon111 commented
> > > Estimation이랑 Order도메인 합친 후에 다시 리뷰하겠습니다!
> > 
> > 
> > Estimation이랑 Order랑 합치게 됐을때 FK로 엮나요? 만약 그렇게 되면 Order나 Estimation이 공통적으로 가지고 있던 프로퍼티들은 Order가 가지는게 맞을까요? 아니면 Estimation이 가지는게 맞을까요?
> > 견적만 있는 상태는 있고, 견적없이 주문만 있는 상태는 없다보니 견적에 프로퍼티들을 추가하는게 맞는것 같은데, 만약 저번에 얘기하신것처럼 배치를 돌려서 주문완료된 견적들은 일정 주기대로 삭제할 예정이라면 얘기가 또 달라질것 같아 질문드립니다!
> > 만약 주문으로 이어진 견적은 삭제되지 않고, 주문으로 이어지지 않은 견적만 삭제되도록 배치 처리를 하면 상관 없을것 같기도 합니다!
> 
> 견적은 주문과는 관계없이 삭제하는 것으로 구상했습니다. 회의 때 제안한 아이디어라면 Estimation의 PK로 Order의 PK를 사용하는 방식을 제안했습니다. 공통적으로 가지는 프로퍼티에 관한건 굳이 클래스를 분리시킬 필요가 있냐의 문제였고, 양쪽에 중복해서 저장하는게 맞을 것 같습니다.


 도메인을 합친다는게 정확히 어떤 의미인가요? 저는 Order의 도메인 객체 안에 Estimation을 포함시키는걸 생각했는데, 말씀하신 맥락대로면 각각의 PK를 사용하고 있으므로 도메인객체 내에서 관계를 엮을 필요가 없어보이는것 같아서 제가 잘못 이해한 부분이 있는것 같아 질문드려요

2023-09-13 12:01 UTC, constwon111 commented on src/main/java/dau/azit/simon/order/controller/SalesOrderController.java
> +		return ResponseEntity.ok(null);
자원 반환해주는것도 동일하게 responseDto를 고민하고 있는데, 오늘 회의때 일관된 형식이 나올 수 있으면 좋을것 같습니다. 그 형식에 맞춰서 생성자원 반환하는 부분하고 단일조회, 리스트 조회하는 부분들의 dto들도 만들어 한번에 업데이트 하면 어떨까 합니다!

2023-09-13 12:01 UTC, constwon111 commented on src/main/java/dau/azit/simon/estimation/domain/Estimation.java
> +	@ManyToOne()
넵!

2023-09-13 12:05 UTC, AnTaeWook commented on src/main/java/dau/azit/simon/order/controller/SalesOrderController.java
> +		return ResponseEntity.ok(null);
좋은 생각입니다람쥐

2023-09-13 12:13 UTC, GrassHopper42 commented
> 도메인을 합친다는게 정확히 어떤 의미인가요? 저는 Order의 도메인 객체 안에 Estimation을 포함시키는걸 생각했는데, 말씀하신 맥락대로면 각각의 PK를 사용하고 있으므로 도메인객체 내에서 관계를 엮을 필요가 없어보이는것 같아서 제가 잘못 이해한 부분이 있는것 같아 질문드려요

Estimation과 Order가 별개의 바운디드 컨텍스트로 분리돼 패키지가 나뉠 필요가 없다는 걸로 지난 회의가 정리되었던 걸로 기억합니다. Estimation과 Order가 별개의 객체로 분리되더라도, OrderLine과 EstimationLine은 같은 객체나 다름 없는데 굳이 분리되어야 하는가에 대한 의문이었습니다.
이를 합쳐서 구현하는 것은 정답은 없습니다만, 제게 아이디어를 구하셨기 때문에 냈던 의견은 Estimation과 Order가 PK를 공유한다던가 하는 식으로 Estimation의 특정 컬럼을 통해 Order를 조회할 수 있도록 하고, Order에 해당 컬럼을 Unique Constraint로 지정해 같은 견적에 대한 주문이 중복 생성되지 않도록 하자는 의견이었습니다.

2023-09-13 12:27 UTC, constwon111 commented
> Estimation과 Order가 별개의 바운디드 컨텍스트로 분리돼 패키지가 나뉠 필요가 없다는 걸로 지난 회의가 정리되었던 걸로 기억합니다. Estimation과 Order가 별개의 객체로 분리되더라도, OrderLine과 EstimationLine은 같은 객체나 다름 없는데 굳이 분리되어야 하는가에 대한 의문이었습니다. 이를 합쳐서 구현하는 것은 정답은 없습니다만, 제게 아이디어를 구하셨기 때문에 냈던 의견은 Estimation과 Order가 PK를 공유한다던가 하는 식으로 Estimation의 특정 컬럼을 통해 Order를 조회할 수 있도록 하고, Order에 해당 컬럼을 Unique Constraint로 지정해 같은 견적에 대한 주문이 중복 생성되지 않도록 하자는 의견이었습니다.


잘 이해가 가지 않습니다. 패키지가 나뉘지 않으면 같은 패키지 안에 두개의 클래스를 구현하라는 말씀이신건가요? 그리고 Estimation과 Order는 별개의 객체로 분리하지만 OrderLine과 EstimatioinLine은 통합해서 쓰자고 말씀해주시는건가요? 

이전 회의때 제가 합치자고 동의했던 부분은 데이터 일관성 측면에서였던걸로 기억합니다. 거의 비슷한 두 데이터가 다른 테이블에 유지될 경우 이 데이터들을 계속 동기화하는데 여러 이슈들이 있을것이라고 생각했습니다. 
본질적으로는 견적과 주문의 책임은 달라 분리하는게 맞다고 생각했지만 어차피 비슷한 데이터들을 계속 가지고 있을 것이므로 이러한 책임을 좀 내려놓되 관리하기(일관성 지키기) 쉽게 하자는 취지로 이해했고, 그러한 측면에서 fk를 말씀드렸었는데 회의 당시에는 그 방법에도 긍정하셨던 것으로 기억합니다.

오늘 회의때 구두로 논의를 명확하게 나누는게 필요할 것 같습니다.

2023-09-15 06:30 UTC, AnTaeWook approved these changes

2023-09-15 12:10 UTC, GrassHopper42 commented on src/main/java/dau/azit/simon/order/domain/SalesOrderLine.java
> +	private String productCode;
코드가 있음에도 ProductId를 지정한 이유는 코드는 변경의 여지가 있기 때문에 코드의 변경에도 상품의 이력을 추적하기 위함입니다. 제품 코드를 통해 참조하기보다는 Id를 통해 참조하는게 합리적일 것 같습니다.

2023-09-15 12:26 UTC, merged